person={'first_name':'Zhang',
		'last_name':'San',
		'age':20, 
		'city':'TianMen'}
print(person)
print(person['first_name'])
print(person['last_name'])
print(person['age'])
print(person['city'])
